# name: Playwright Tests
# on:
#    push:
#      branches: [ main, master]
#    pull_request: 
#      branches: [ main, master]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: 18
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#     - uses: actions/upload-artifact@v4
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30   
name: Playwright Tests
on:
   push:
     branches: [ main, master]
   pull_request: 
     branches: [ main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
        if: always()
      - run: docker build -f Dockerfile.focal -t plimage .
      - run: docker run -d --name plcontainer plimage
      - run: sudo docker cp plcontainer:./tests/allure-results allure results
      - uses: actions/upload-artifact@main
        with:
          name: allure-results
          path: allure-results
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@main
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
        




         